{
  "hash": "7fd4852fe0a08273e2b569604cb98c05",
  "result": {
    "engine": "knitr",
    "markdown": "---\nfilters:\n  - line-highlight\nexecute: \n  freeze: auto\n---\n\n\n\n# UK Museums: highlighting line charts with {gghighlight} {#sec-museums}\n\nIn this chapter we'll consider different ways of visualising data that varies over time, aiming to avoid *spaghetti charts*, with the help of the {gghighlight} extension package\\index{gghighlight}.\n\n## Data\n\nThe [Mapping Museums](https://museweb.dcs.bbk.ac.uk/data) project [@museums_data] has collected data relating to over 4,000 museums in the UK, covering museums from 1960 onward. The data can be downloaded from the Mapping Museums website at [www.mappingmuseums.org](www.mappingmuseums.org). It was also used as a \\#TidyTuesday\\index{TidyTuesday} [@tidytuesday] data set in November 2022, and we'll use that version for this chapter.\n\nLet's start by reading in the data and looking at the definitions of the variables: \\index{readr!read\\_csv}\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmuseums <- readr::read_csv(\"data/museums.csv\")\n```\n:::\n\n\n\nThe data contains information for 35 different variables on 4191 museums. After the first `museum_id` columns, the next 8 columns provide information on the location of the museum - including address and co-ordinates. The next set of columns provides information about the museums such as whether it's an accredited museum, how it's governed, what types of items it has, and when it was open. Since this is a collated data set, information is also provided on the original source of the data for some of these variables. The remaining columns provide information on the area in which the museum is located, including information about different deprivation indices and geodemogrqaphic group (type of area e.g. `\"University Towns and Cities\"`). A full glossary of the terms used can be found on the Mapping Museums website at [museweb.dcs.bbk.ac.uk/glossary](https://museweb.dcs.bbk.ac.uk/glossary).\n\n## Exploratory work\n\nLet's start exploring what these variables look like!\n\n::: {.callout-note icon=false appearance=\"simple\"}\n\nRemember that you can use `View(museums)` to inspect the data in a more human-readable format.\n\n:::\n\n### Data exploration\n\nThere are many different aspects of this data we could inspect:\n\n* How are museums spread out across the UK? Is there a higher concentration of museums in more affluent areas?\n* What types of museums are most prevalent in the UK? Does the vary based on whether the museum is accredited?\n* How is the number of museums open changing over time? Are more museums opening than closing?\n\nSome of the variables, such as `DOMUS_Subject_Matter` have quite a lot of missing values which makes \n\nAlthough these definitely warrant further exploration,\n\nGiven the wealth of information around deprivation indices (8 different variables), that's the first aspect of the data that jumps out. How does the number of museums vary per index of deprivation?\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbarplot(\n  table(museums$Area_Deprivation_index),\n  cex.axis = 0.5,\n  cex.names = 0.5\n)\n```\n\n::: {.cell-output-display}\n![](uk-museums_files/figure-pdf/museums-barplot-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n\nHere, `1` is the most deprived, and `10` is the least deprived. This is quite an interesting relationship - there have been more museums in places with a moderate level of deprivation compared to higher or lower level. This might feel a little bit counter-intuitive, we might expect there to be more museums in more affluent areas. But looking at the total number of museums in the data per index of deprivation doesn't tell us the whole story. How many of these museums were open at once? How many are still open today? \n\nTo get a better understanding of the relationship between deprivation and the number of museums, we could look at how the number of museums changed for each index of deprivation has changed since 1960 (the earliest date in the data set). Then we might be able to tell whether more are opening or closing, and how this varies across the different levels of deprivation.\n\n### Exploratory sketches\n\nWe have 10 deciles of deprivation, so we'll have 10 time series that we want to plot that show the number of museums over time. There are different options for plotting time series like this. We need to think about some different choices:\n\n* What type of *geometry* will we use? Lines, points, shaded areas? Lines are the most common approach for \n* Do we plot all 10 lines on the same chart and use color to denote the different levels of deprivation?\n* Or do we use faceting to split it into multiple smaller plots by deprivation index?\n\nIf we go with line charts, and faceting by deprivation index, that might look something like this: \n\n![](images/sketch-museums.png){#fig-museums-sketch fig-align=\"center\" fig-cap=\"Initial sketch of a facetted plot showing change over time for each level of deprivation.\"}\n\nWe could achieve something this type of plot using `geom_line()` and `facet_wrap()` from {ggplot2} \\index{ggplot2!facet\\_wrap} \\index{ggplot2!geom\\_line}. We've talked about faceting before in both Chapter ...(1) and Chapter ...(2) but we haven't really thought much about the layouts of those facets. In Chapter ...(1), we used faceting with only 3 categories, where the layout choice is fairly obvious: either one column or one row. In Chapter ...(2), we used `facet_grid()` where the number of levels in two factor variables define the number of rows and columns. Here, we have a little bit more flexibility and we might want to think about controlling that layout. \\index{ggplot2!facet\\_grid}\n\nIf we leave it to the default options, {ggplot2} usually tries to coerce it into something *square-ish*. Here, it would likely give us a 3x4 grid filled with 10 plots (for the 10 levels of deprivation) and 2 blank spaces. It's not always possible, but plots without those blank spaces often look a lot cleaner and tidier. We could do either a 5x2 (or 2x5) grid, or a 10x1 (or 1x10) grid to fit our small multiple plots into a perfect rectangle. A 5x2 grid works better here since we don't want to make a very wide but very short plot.\n\n## Preparing a plot\n\nSo let's get started on preparing the data to create this plot!\n\n### Data wrangling\n\nThis is one of those very *real* datasets - the data wrangling is not straightforward for the data. In fact, the two columns relating to opening and closing dates are the two that will require the most attention.\n\nFirst, let's drop any columns that we don't actually need using the `select()` function from {dplyr} - we only need the `Year_opened`, `Year_closed`, and `Area_Deprivation_index` columns to calculate the number of museums open each year \\index{dplyr!select}. There are a few `NA` values in the `Area_Deprivation_index` column so we'll drop those rows using `drop_na()` from {tidyr} \\index{tidyr!drop\\_na}.\n\nNow let's start dealing with the year columns. If you look at the values, you'll notice that they're not exactly what you'd expect in a *year* column:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(museums$Year_opened, 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"2012:2012\" \"1971:1971\" \"1984:1984\" \"1971:1971\"\n```\n\n\n:::\n\n```{.r .cell-code}\nhead(museums$Year_closed, 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"9999:9999\" \"2007:2017\" \"9999:9999\" \"2012:2012\"\n```\n\n\n:::\n:::\n\n\n\nEach entry is in fact two years, separated by a `:`. According to the Mapping Museums glossary, this is because these are actually date ranges. For some museums, it wasn't possible to establish an exact opening or closing date, and instead a date range is given based on partial information. For example, a value of `\"2007:2017\"` means the museum opened (or closed) sometime between 2007 and 2017.\n\nLet's separate out these year values into four columns instead of two using the `separate()` function from {tidyr} \\index{tidyr!separate}. We separate based on the `:`, and create two new columns, `opened1` and `opened2`. from the `Year_opened` column. We do the same thing for the `Year_closed` closed column. We also want to make sure that these new columns are numeric rather than character columns, so we use `mutate()` and `across()` from {dplyr} to convert them using `as.numeric()` \\index{dplyr!mutate} \\index{dplyr!across}. We can also convert the `Area_Deprivation_index` to a factor rather than a numeric and make sure the order is correct. \n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmuseum_subset <- museums |>\n  dplyr::select(\n    Year_opened, Year_closed, Area_Deprivation_index\n  ) |>\n  tidyr::drop_na() |>\n  tidyr::separate(\n    Year_opened,\n    into = c(\"opened1\", \"opened2\"),\n    sep = \":\"\n  ) |>\n  tidyr::separate(\n    Year_closed,\n    into = c(\"closed1\", \"closed2\"),\n    sep = \":\"\n  ) |>\n  dplyr::mutate(\n    dplyr::across(\n      c(opened1, opened2, closed1, closed2), as.numeric\n    ),\n    Area_Deprivation_index = factor(Area_Deprivation_index, levels = 1:10)\n  )\n```\n:::\n\n\n\n::: {.callout-note icon=false appearance=\"simple\"}\n\nYou could alternatively use `separate_wider_delim()` instead of `separate()`. \\index{tidyr!separate\\_wider\\_delim}\n\n:::\n\nNow we need to think about how to deal with all of these *year* columns: \n\n* If the date before the `:` and the date after the `:` are the same, we want to treat it as an exact year and only keep one value.\n* If the dates do not match, we need to decide a way of choosing which year to use. The simplest approach is to take the midpoint of the date range. \n* If the value in the `Year_closed` column is `\"9999:9999\"`, this means that the museum is still open. \n\nLet's start with the last of these issues first. For the `closed1` and `closed2` columns, if the value is `\"9999\"`, we'll convert it to an `NA_real_` value and otherwise leave it as it is. We can do this using a combination of `mutate()`, `across()`, and `if_else()` from {dplyr} \\index{dplyr!mutate} \\index{dplyr!across} \\index{dplyr!if\\_else}.\n\nThe remaining two issues can be dealt with at the same time using `case_when()` from {dplyr} \\index{dplyr!case\\_when}. We can create a new column called `closed` which:\n\n* if `closed1` and `closed2` are equal, takes this value;\n* if `closed1` and `closed2` are not equal, takes the value in the middle (rounded so that we work only with whole year values).\n\nThe same approach is then applied to create another new column called `opened`. There are no instances in the data where one of the closing dates is `NA` but the other is not, so we don't need to worry about that. We can also tidy up the output by dropping any columns we don't need, renaming the `Area_Deprivation_index` to something a little bit shorter and easier to work with, and arranging the data by level of deprivation. \\index{dplyr!rename} \\index{dplyr!arrange} \\index{dplyr!select} \n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmuseum_data <- museum_subset |> \n  dplyr::mutate(dplyr::across(\n    c(closed1, closed2),\n    ~ dplyr::if_else(.x == 9999, NA_real_, .x)\n  )) |>\n  dplyr::mutate(closed = dplyr::case_when(\n    closed1 == closed2 ~ closed1,\n    closed1 != closed2 ~ round((closed2 + closed1) / 2)\n  )) |>\n  dplyr::mutate(opened = dplyr::case_when(\n    opened1 == opened2 ~ opened1,\n    opened1 != opened2 ~ round((opened2 + opened1) / 2)\n  )) |>\n  dplyr::select(Area_Deprivation_index, opened, closed) |>\n  dplyr::rename(deprivation = Area_Deprivation_index) |>\n  dplyr::arrange(deprivation)\n```\n:::\n\n\n\nThis gives us data that looks like this:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(museum_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 x 3\n  deprivation opened closed\n  <fct>        <dbl>  <dbl>\n1 1             1988     NA\n2 1             1984   2007\n3 1             1983     NA\n4 1             1969     NA\n5 1             1989     NA\n6 1             1995     NA\n```\n\n\n:::\n:::\n\n\n\nWhat we want to know is how many museums were open in a given year for each level of deprivation. Let's create a function that takes three inputs: a year of interest, a level of deprivation, and the `museum_data`. Inside the function, we can then `filter()` the data to only the level of deprivation we're interested in. Then we can count how many museums opened before or in the year we're interested in, and then same for the how many museums closed (remembering to deal with the `NA` values for museums that are still open). The difference between the two will be how many were open in that year. \\index{dplyr!filter}\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnum_year <- function(year, dep, data = museum_data) {\n  df <- dplyr::filter(data, deprivation == dep)\n  num_open <- sum(df$opened <= year)\n  num_closed <- sum(df$closed <= year, na.rm = TRUE)\n  diff <- num_open - num_closed\n  return(diff)\n}\n```\n:::\n\n\n\nLet's test it works:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnum_year(1980, 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 186\n```\n\n\n:::\n:::\n\n\n\nThere were 186 museums open in 1980. Now, we need to run this function for every combination of year (from `1960` to `2021`) and deprivation level (from `1` to `10`). There are many different ways of doing this in R, and we're going to use the {purrr} package [@purrr]. We start by creating to variables with sequences of years and levels of deprivation - this is useful for testing if the code works because we can easily change it to a smaller number of years. Then we use `expand.grid` to create a `data.frame` with all of the combinations and pass this in as the first argument to `pmap_vec` from {purrr}. The second argument to `pmap_vec` is the function we want to apply (`num_year()`) that we defined above), where the first argument of `num_year()` comes from the first column of the grid of values, and the second argument from the second column. We can then convert the output into a matrix where each column is a level of deprivation, and each row is a year. \\index{purrr!pmap\\_vec} \n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nall_years <- 1960:2021\ndeps <- 1:10\noutput <- purrr::pmap_vec(\n  expand.grid(all_years, deps),\n  ~ num_year(year = .x, dep = .y)\n)\nresults <- matrix(output,\n  nrow = length(all_years),\n  byrow = FALSE\n)\ncolnames(results) <- 1:10\n```\n:::\n\n\n\nNow, our data looks like this:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(results)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       1  2   3   4   5   6   7   8  9 10\n[1,] 103 78 110 125 125 124 122 110 76 51\n[2,] 103 78 112 132 125 131 126 113 77 53\n[3,] 104 78 113 138 129 135 129 117 83 58\n[4,] 105 79 118 140 136 140 130 123 85 60\n[5,] 105 79 122 144 139 145 135 126 86 64\n[6,] 106 80 123 148 143 147 137 128 89 67\n```\n\n\n:::\n:::\n\n\n\nWe're almost ready to start plotting our data! We just need to convert this into a `tibble()` (or `data.frame`), add the `year` column using `mutate()`, and put the data into a long format using `pivot_longer` from {tidyr} \\index{tibble!as\\_tibble} \\index{dplyr!mutate} \\index{tidyr!pivot\\_longer}. We want to end up with a 3 column data set, where the 3 columns are: `year`, `deprivation`, and `museums` (number of open museums).\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot_data <- results |>\n  tibble::as_tibble() |>\n  dplyr::mutate(year = all_years) |>\n  tidyr::pivot_longer(\n    -year,\n    names_to = \"deprivation\",\n    values_to = \"museums\"\n  ) |>\n  dplyr::mutate(\n    deprivation = factor(deprivation, levels = 1:10)\n  )\n```\n:::\n\n\n\n### The first plot\n\none of most common approaches - although already thinking about facets.worth seeing what it looks like - maybe want to highlight just one e.g. most deprived\n\n\\index{ggplot2!geom\\_line}\n\n\\index{line chart}\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ggplot2)\nggplot(\n  data = plot_data,\n  mapping = aes(x = year, y = museums, color = deprivation)\n) +\n  geom_line()\n```\n\n::: {.cell-output-display}\n![A line chart of total number of museums open per year for each level of deprivation, with the overlapping lines resembling spaghetti!](uk-museums_files/figure-pdf/fig-museums-basic-plot-1-1.pdf){#fig-museums-basic-plot-1 fig-pos='H'}\n:::\n:::\n\n\n\nspeghetti plots\n10 is a fairly large number of colors\n\nSince the colors in the legend are in different order\n\nlet's try separating out into different facets - see Chapter 1 (cross-ref needed)\ncolor to fill\ngeom_area \\index{ggplot2!geom\\_area} \\index{ggplot2!facet\\_wrap}\n\n\\index{area chart}\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(\n  data = plot_data,\n  mapping = aes(x = year, y = museums, fill = deprivation)\n) +\n  geom_area() +\n  facet_wrap(~deprivation, nrow = 2)\n```\n\n::: {.cell-output-display}\n![An area chart of total number of museums open per year for each level of deprivation, with the each deprivation level in a different facet.](uk-museums_files/figure-pdf/fig-museums-basic-plot-2-1.pdf){#fig-museums-basic-plot-2 fig-pos='H'}\n:::\n:::\n\n\n\nthis was the initial design i started with, but hard to compare\nlet's go back to geom_line \\index{gghighlight!gghighlight} \\index{line chart}\n\n\n\n::: {.cell source-line-numbers='7'}\n\n```{.r .cell-code}\nggplot(\n  data = plot_data,\n  mapping = aes(x = year, y = museums, color = deprivation)\n) +\n  geom_line() +\n  facet_wrap(~deprivation, nrow = 2) +\n  gghighlight::gghighlight(use_direct_label = FALSE)\n```\n\n::: {.cell-output-display}\n![A line chart of total number of museums open per year for each level of deprivation, with the each deprivation level in a different facet and individual lines highlighted.](uk-museums_files/figure-pdf/fig-museums-basic-plot-3-1.pdf){#fig-museums-basic-plot-3 fig-pos='H'}\n:::\n:::\n\n\n\nsome of them started higher lower levels, let's look at perc change instead\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlookup <- plot_data |>\n  dplyr::filter(year == 1960) |>\n  dplyr::select(deprivation, museums)\n\nnew_plot_data <- plot_data |>\n  dplyr::left_join(lookup, by = \"deprivation\") |>\n  dplyr::rename(\n    museums = museums.x,\n    museums_1960 = museums.y\n  ) |>\n  dplyr::mutate(\n    change = (100 * (museums - museums_1960) / museums_1960)\n  ) |>\n  dplyr::select(year, deprivation, change)\n```\n:::\n\n\n\nlet's plot instead\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbase_plot <- ggplot(\n  data = new_plot_data,\n  mapping = aes(x = year, y = change, color = deprivation)\n) +\n  geom_line() +\n  facet_wrap(~deprivation, nrow = 2) +\n  gghighlight::gghighlight(use_direct_label = FALSE)\nbase_plot\n```\n\n::: {.cell-output-display}\n![A line chart of percentage increase in museums (compared to 1960) for each level of deprivation, with the each deprivation level in a different facet and individual lines highlighted.](uk-museums_files/figure-pdf/fig-museums-basic-plot-4-1.pdf){#fig-museums-basic-plot-4 fig-pos='H'}\n:::\n:::\n\n\n\n## Advanced styling\n\nget rid of legend\ncolors aren't great\n\n### Colors\n\n{viridis} [@viridis] \\index{viridis!scale\\_color\\_viridis}\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbg_col <- \"#fafafa\"\ntext_col <- \"black\"\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ncol_plot <- base_plot +\n  viridis::scale_color_viridis(discrete = TRUE, direction = -1)\ncol_plot\n```\n\n::: {.cell-output-display}\n![An updated version of the previous chart with colors chosen from the {viridis} R package.](uk-museums_files/figure-pdf/fig-museums-style-plot-1-1.pdf){#fig-museums-style-plot-1 fig-pos='H'}\n:::\n:::\n\n\n\n### Text and fonts\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsysfonts::font_add_google(\"Raleway\", \"raleway\")\nshowtext::showtext_auto()\nshowtext::showtext_opts(dpi = 300)\nbody_font <- \"raleway\"\n```\n:::\n\n\n\n{sysfonts}\\index{sysfonts}\n{showtext}\\index{showtext}\n\n\\index{sysfonts!font\\_add\\_google}\n\\index{showtext!showtext\\_auto}\n\\index{showtext!showtext\\_opts}\n\nText \n\nmake sure text is correct one\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntitle <- \"Are there fewer museums opening in more deprived areas?\"\nst <- \"The change in the estimated number of open museums since 1960 is significantly lower in areas with higher levels of deprivation. *Since around 2000, the number of open museums has stagnated across all areas, regardless of deprivation index. However, the rate of growth prior to this stagnation is lower in more deprived areas.\"\ncap <- \"*The Index of Multiple Deprivation (IMD) measures the relative deprivation of geographic areas in the UK, aggregating different dimensions (income, employment, education, health, crime, housing, and living environment). The index ranges from 1 (most deprived) to 10 (least deprived).<br><br>**In some instances it has been impossible to establish an exact opening or closing date for a museum. In these cases, museums’ opening and closing dates are taken to be the mid point of a specified range of possible dates.<br><br>N. Rennie | Data: museweb.dcs.bbk.ac.uk\"\n```\n:::\n\n\n\n\\index{ggtext!element\\_textbox\\_simple}\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntext_plot <- col_plot +\n  labs(\n    title = title, subtitle = st, caption = cap,\n    x = \"\",\n    y = \"% change in estimated number of\\nopen museums since 1960**\"\n  )\n```\n:::\n\n\n\n### Adjusting themes\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ggtext)\ntext_plot +\n  scale_y_continuous(limits = c(0, 300)) +\n  coord_cartesian(expand = FALSE) +\n  theme_minimal(base_size = 7, base_family = body_font) +\n  theme(\n    legend.position = \"none\",\n    plot.title.position = \"plot\",\n    plot.caption.position = \"plot\",\n    panel.spacing = unit(1, \"lines\"),\n    plot.margin = margin(10, 15, 10, 10),\n    plot.background = element_rect(\n      fill = bg_col, color = bg_col\n    ),\n    panel.background = element_rect(\n      fill = bg_col, color = bg_col\n    ),\n    plot.title = element_textbox_simple(\n      color = text_col,\n      lineheight = 0.5,\n      size = rel(1.2),\n      face = \"bold\",\n      margin = margin(b = 5)\n    ),\n    plot.subtitle = element_textbox_simple(\n      color = text_col,\n      lineheight = 0.5\n    ),\n    plot.caption = element_textbox_simple(\n      hjust = 0,\n      color = text_col,\n      lineheight = 0.5\n    ),\n    axis.text = element_text(\n      color = text_col,\n      lineheight = 0.5\n    )\n  )\n```\n\n::: {.cell-output-display}\n![A styled version of the previous plot - with a custom font, colored background, and better spacing.](uk-museums_files/figure-pdf/fig-museums-style-plot-3-1.pdf){#fig-museums-style-plot-3 fig-pos='H'}\n:::\n:::\n\n\n\n## Reflection\n\nWhat would I want to change about this plot? color probably not needed\n\n::: {.content-visible when-format=\"html\"}\n\nEach plot created during the process of developing the original version of this visualisation was captured using {camcorder}, and is shown in the gif below. If you'd like to learn more about how {camcorder} can be used in the data visualisation process, @sec-camcorder.\n\n![](images/uk-museums.gif){fig-align=\"center\"}\n\n:::\n",
    "supporting": [
      "uk-museums_files\\figure-pdf"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {
      "knitr": [
        "{\"type\":\"list\",\"attributes\":{},\"value\":[]}"
      ]
    },
    "preserve": null,
    "postProcess": false
  }
}