project:
  type: book
  render:
    - "*.qmd"
    - "!drafts/"
execute: 
  eval: true
  echo: true
  warning: false
fig-align: center
fig-height: 4
fig-width: 6

bibliography: references.bib

book:
  title: "The #TidyTuesday Cookbook"
  subtitle: "A case study approach to learning data visualisation with {ggplot2}"
  author: "Nicola Rennie"
  description: |
    Learn how to create data visualisations in R.
    
  chapters:
  - index.qmd
  - introduction.qmd
  
  - part: weird-wonderful.qmd
    chapters:
        - technology-adoption.qmd

  - references.qmd
  
format:
  html:
    code-link: true
  pdf:
    number-depth: 3
    toc-depth: 3
    include-in-header:
      - file: header.tex

