project:
  type: book
  output-dir: docs
  render:
    - "*.qmd"
    - "!drafts/"
execute: 
  eval: true
  echo: true
  warning: false
fig-align: center
fig-height: 4
fig-width: 6
appendix-style: plain

bibliography: references.bib
nocite: |
  @*
  
book:
  title: "The #TidyTuesday Cookbook"
  subtitle: "A case study approach to learning data visualisation with {ggplot2}"
  author: "Nicola Rennie"
  description: |
    Learn how to create data visualisations in R.
  output-file: "Manuscript"
    
  chapters:
    - index.qmd
    - author.qmd
    - introduction.qmd
    - part: common-charts.qmd
      chapters:
        - programming-languages.qmd
        - bee-colony-losses.qmd
        - uk-museums.qmd
    - part: text-fonts.qmd
      chapters:
        - cats.qmd
    - part: spatial.qmd
      chapters:
        - doctors-ageing-population.qmd
    - part: images.qmd
      chapters:
        - lemurs.qmd
        - global-seafood.qmd
    - part: weird-wonderful.qmd
      chapters:
        - technology-adoption.qmd
    - conclusion.qmd
    - references.qmd
    - appendix.qmd
  
format:
  html:
    code-link: true
    toc-title: "Contents"
    highlight-style: tango
    urlcolor: "#b20e10"
    linkcolor: "#b20e10"
    theme: lux
    default-image-extension: png
    fig-width: 5
    fig-asp: 0.67
    fig-align: center
    fig-dpi: 300
    fig-format: png
  pdf:
    documentclass: krantz
    number-depth: 3
    toc-depth: 3
    toc-title: "Contents"
    linkcolor: "black"
    urlcolor: "black"
    citecolor: "black"
    highlight-style: tango
    fig-width: 5
    fig-asp: 0.67
    fig-align: center
    fig-dpi: 300
    include-in-header:
      - file: preamble.tex
    include-before-body:
        text: |
           \pagestyle{plain}
           \pagenumbering{roman}
    include-after-body: 
      text: |
        \printindex

