project:
  type: book
  output-dir: docs
  render:
    - "*.qmd"
    - "!drafts/"
execute: 
  eval: true
  echo: true
  warning: false
fig-align: center
fig-height: 4
fig-width: 6
appendix-style: plain

bibliography: references.bib
nocite: |
  @*
  
book:
  title: "The Art of Data Visualization with ggplot2"
  subtitle: "The TidyTuesday Cookbook"
  cover-image: "images/cover.png"
  author: "Nicola Rennie"
  google-analytics:
    tracking-id: "G-1SWN5BH1PZ"
    anonymize-ip: true
    
  chapters:
    - index.qmd
    - author.qmd
    - introduction.qmd
    - part: common-charts.qmd
      chapters:
        - programming-languages.qmd
        - museums.qmd
        - bee-colonies.qmd
        - animal-intakes.qmd
    - part: text.qmd
      chapters:
        - wind-turbines.qmd
        - cats.qmd
        - nobel-laureates.qmd
    - part: images.qmd
      chapters:
        - lemurs.qmd
        - r-packages.qmd
    - part: spatial.qmd
      chapters:
        - doctors.qmd
        - time-zones.qmd
        - us-elections.qmd
    - other-tricks.qmd
    - references.qmd
    - appendix.qmd
  
format:
  html:
    code-link: true
    code-overflow: wrap
    toc-title: "Contents"
    highlight-style: tango
    urlcolor: "#508080"
    linkcolor: "#508080"
    theme: [litera, styles.scss]
    default-image-extension: png
    fig-width: 5
    fig-asp: 0.67
    fig-align: center
    fig-dpi: 300
    fig-format: png
