project:
  type: book
  render:
    - "*.qmd"
    - "!drafts/"
execute: 
  eval: true
  echo: true
  warning: false
fig-align: center
fig-height: 4
fig-width: 6

bibliography: references.bib

book:
  title: "The #TidyTuesday Cookbook"
  subtitle: "A case study approach to learning data visualisation with {ggplot2}"
  author: "Nicola Rennie"
  description: |
    Learn how to create data visualisations in R.
    
  chapters:
    - index.qmd
    - introduction.qmd
    - part: common-charts.qmd
      chapters:
        - uk-museums.qmd
    - part: text-fonts.qmd
    - part: spatial.qmd
      chapters:
        - doctors-ageing-population.qmd
    - part: images.qmd
    - part: weird-wonderful.qmd
      chapters:
        - technology-adoption.qmd

    - references.qmd
  
format:
  html:
    code-link: true
    toc-title: "Contents"
    highlight-style: tango
  pdf:
    documentclass: krantz
    number-depth: 3
    toc-depth: 3
    toc-title: "Contents"
    highlight-style: tango
    include-in-header:
      - file: preamble.tex

