project:
  type: book
execute: 
  eval: true
  echo: true
  warning: false
fig-align: center
fig-height: 4
fig-width: 6

bibliography: references.bib

book:
  title: "The #TidyTuesday Cookbook"
  subtitle: "A Case Study Approach to Learning Data Visualisation with {ggplot2}"
  author: "Nicola Rennie"
  description: |
    Learn how to create data visualisations in R.
    
  chapters:
  - index.qmd
  - chapters/00-introduction.qmd
  
  - part: Common charts don't need to be boring!
    chapters: 
    - chapters/01-programming-languages.qmd