# Author {#author .unnumbered}

[Nicola Rennie](https://nrennie.rbind.io/) is a Lecturer in Health Data Science within the [Centre for Health Informatics, Computing, and Statistics](https://chicas.lancaster-university.uk/index.html) at Lancaster University. She holds a PhD in Statistics and Operational Research, which focused on analysing and visualising transport demand. Her current research is focused on applications of statistics and machine learning to health-related data, communicating statistics, and the effective teaching of data science. She has experience of teaching at both undergraduate and postgraduate level, in courses covering fundamentals of data science, population health, and statistical programming. Nicola has also previously worked in data science consultancy, and delivered training courses covering topics including advanced data visualisation with R, statistical modelling, and reproducible reporting. She is the author and maintainer of several R packages, including multiple {ggplot2} extension packages. Nicola is a regular speaker at R and data science meetups, is the current chapter organiser of R-Ladies Lancaster, and is part of the R-Ladies Global Team. She is co-author of the Royal Statistical Society's [Best Practices for Data Visualisation Guide](https://royal-statistical-society.github.io/datavisguide/), and an active member of the Royal Statistical Society. Several of her data visualisations have been long-listed at the Information is Beautiful Awards.

\pagenumbering{arabic}
