---
filters:
  - line-highlight
execute: 
  freeze: auto
---

# Chapter 6: Custom social media captions with Font Awesome icons {#sec-chap6}

::: {.callout-caution}

This chapter is coming soon!

:::


## Advanced styling

### Text and fonts

### Loading Font Awesome Fonts

This needs fixed 

```{r}
sysfonts::font_add(
    family = "Font Awesome 6 Brands",
    regular = file.path("fonts", "Font-Awesome-6-Brands-Regular-400.otf"),
  )
```


### Using Font Awesome icons

```{r}
social_caption <- function(twitter = "@nrennie35",
                           mastodon = "fosstodon.org/@nrennie",
                           linkedin = "nicola-rennie",
                           github = "nrennie",
                           icon_colour = nr_dark,
                           font_colour = nr_dark,
                           bg_colour = nr_light,
                           font_family = "Commissioner") {
  icons <- list(
    twitter = "&#xf099",
    mastodon = "&#xf4f6",
    linkedin = "&#xf08c",
    github = "&#xf09b"
  )
  social <- list(
    twitter = twitter,
    mastodon = mastodon,
    linkedin = linkedin,
    github = github
  )
  social <- social[!is.na(social)]
  caption <- ""
  for (name in names(social)) {
    icon <- icons[name]
    info <- social[name]
    html <- glue::glue("<span style='font-family:\"Font Awesome 6 Brands\";color:{icon_colour};'>{icon};</span><span style='color:{bg_colour};'>.</span><span style='font-family:{font_family};color:{font_colour};'>{info}</span><span style='color:{bg_colour};'>..</span>") # nolint
    caption <- paste0(caption, html)
  }
  return(caption)
}
```
