# Common charts don't need to be boring! {#sec-common-intro .unnumbered}

When you say the word *chart*, there are a few common types of plot that spring to mind: bar charts, scatter plots, and line charts. The fact that these charts are common often makes them good choices for communicating data because they don't require as much effort from a reader to understand. However, some chart designers may see these as *boring* charts because they don't require a lot of time or effort to create, and they're very standard. This section discusses some examples of these common charts, and shows you how to elevate them to become anything but boring!

* [Chapter]{.content-visible when-format="html"} @sec-programming will teach you how to make a dumbbell chart with {ggplot2}, and discuss styling charts thematically based on the data they contain.

* [Chapter]{.content-visible when-format="html"} @sec-museums covers line charts, including how to retain clarity and enable better comparisons when plotting many lines.

* [Chapter]{.content-visible when-format="html"} @sec-bees describes the process of transforming data to present it in a different way, and how to arrange a grid of small multiple charts based on different categories.

* [Chapter]{.content-visible when-format="html"} @sec-technology discusses how to use the {ggforce} extension package to build your own customized charts, and convert a bar chart into a gauge chart. 

This section also covers loading fonts into R, and installing packages from GitHub. 