# Working with images {#sec-images-intro .unnumbered}

Using images in charts can make them more eye-catching and engaging. They can also provide context to the data, especially if images (such as logos) may be more easily recognizable than plain text. Images often need some level of processing before being *chart-ready*, and this section aims to illustrate that you don't necessarily need image processing software, and that you can do many simple image operations directly in R.

* [Chapter]{.content-visible when-format="html"} @sec-lemurs describes two packages for working with images in R: **`magick`** and **`imager`**. You will learn how to read images into R and how to manipulate images by cropping them or making specific pixels transparent. You'll also see how these two different image packages can be used together.

* [Chapter]{.content-visible when-format="html"} @sec-r-pkgs illustrates how to work with multiple images, and how to read in and plot them in a data-driven way. 

This section also includes further discussion about dealing with missing data, as well as how to choose effective and accessible color palettes. It also illustrates an alternative package for working with fonts in R.