# Preface {.unnumbered}

::: {.content-visible when-format="html"}

::: {.callout-note icon=false appearance="simple"}

Welcome to the online version of **The #TidyTuesday Cookbook** by [Nicola Rennie](https://nrennie.rbind.io/).

This book is currently a work-in-progress.

:::

:::

Welcome to *The #TidyTuesday Cookbook*. \#TidyTuesday is a weekly social data project which aims to make learning to work with data easier, by providing real-world datasets. Participants are encouraged to explore the data shared via [GitHub](https://github.com/rfordatascience/tidytuesday) each week, create an output such as a data visualization, and share their output alongside their code, with the community. 

After three years of weekly contributions, I've worked with around 150 datasets and created over 150 data visualizations. Each chapter of this book will cover a different data visualisation, showing: the data exploration process; the choice of data visualisation type; the initial design ideas with hand-drawn sketches; the first build of a plot; and the iterative process of styling plots. For each plot, full R code is be provided and explained for each step of the creative process. None of the visualizations you'll see were created specifically for this book - each one is an original data visualization created using real \#TidyTuesday datasets over a series of years. Think of each chapter as a case study starting with a new data set you've never seen before, and working through a process to get to an insightful, artistic visualization. This book is all about that process. Sometimes the data is messy. Sometimes the code is *hacky*. Sometimes, upon reflection, the data could be visualized better. 

Data visualization can be a very effective and efficient means of communicating information. Visualizing your data typically serves one of two purposes: (i) as part of exploratory analysis to help uncover discrepancies in data and identify interesting relationships to measure; or (ii) to communicate key insights and messages to a broader audience. The case-study nature of this book means that we'll talk about both of these aspects, though we 'll focus mostly on the second. Choosing an appropriate type of visualization and making careful choice about design can clarify the message you are trying to convey to a reader. That does not necessarily mean that every chart must follow a set of *rules* and stick to a rigid format. Instead, data visualization is a blend of science and creativity - many of the key *landmark* data visualizations held up as excellent examples don't fit into the standard categories of bar charts, scatter plots, or line graphs. 

That being said, the visualizations in this book are not necessarily always the most effective choice of visualization for the data and relationship shown. Rather, this book aims to show you examples of the end-to-end process of creating data visualizations, with a focus on the technical details of building them in R. You'll see some non-standard solutions and unusual ideas that you can use to transform your data visualizations.

## Who is this book aimed at? {.unnumbered}

This book is primarily aimed at those who wish to develop their data visualization skills in R. Readers of this book may find a basic knowledge of R, more specifically of the {tidyverse} ecosystem, useful - although all code used in examples is fully explained. Readers do not need to be experienced in {ggplot2}, though this book will also be of interest to those who are. This book will also be of interest to those who are already familiar with R (including {ggplot2}), and wish to develop their skills in designing data visualizations further. It will also interest those who already design data visualizations using other tools, and want to learn how to do the equivalent in R.

There are many different versions of R, many different packages in R, and many different styles of writing code - and there isn't a single *best* way of doing things. You may write code differently from the way you see it written in this book, and that's perfectly fine. Throughout the book, a few choices have been made to keep code consistent:

* In R, the pipe operator *takes the thing on its left and passes it along to the function on its right* [@r4ds]. You can find a full description of the pipe operator in [R for Data Science](https://r4ds.hadley.nz/data-transform#sec-the-pipe). The pipe\index{pipe} (`%>%`) was first introduced to R via the {magrittr}\index{magrittr} package. Since version 4.1.0 of R, a version of the pipe (`|>`) has existed in base R. The base R version of the pipe is used throughout the book. Although there are some difference between the two version of the pipe, in this book, they can be used interchangeably. 
* Namespacing\index{namespacing} (the pre-fixing of functions with the package name and `::`) is used for all packages except {ggplot2} and base R packages. Namespacing is useful for two reasons (i) from a learning perspective, it makes it easier to recognise where functions come from and how they connect together, and (ii) from a programming perspective, it reduces conflicts and errors - something we all want less of!
* All software requirements, including a complete list of package versions, can be found in the Appendix.

You may also notice that some of the final images differ slightly from those initially created and published on social media. You might also find some small differences in the code used to produce them if you compare the contents of this book to original scripts in the [GitHub repository](https://github.com/nrennie/tidytuesday). These differences are likely due to one of four reasons: 

* Packages have since been updated and code has been changed to use newer syntax. Many of the code changes relate to changes in {ggplot2} version 3.5.0;
* Some aspects have been omitted from a visualization to avoid explaining *everything* in Chapter 1 - but those aspects are all covered and linked to in later chapters;
* After many years of practice, there may be more efficient ways of re-writing code from some of the earlier plots. Any changes are clearly labelled and discussed;
* Some images may be different due to copyright reasons.

