---
title: "Programming Languages"
format: html
execute: 
  eval: true
  echo: true
  warning: false
fig-align: center
fig-height: 4
fig-width: 6
---

Packages required for this 

* dplyr
* ggplot2
* ggtext
* readr
* showtext
* sysfonts
* tidyr

Original code: [https://github.com/nrennie/tidytuesday/blob/main/2023/2023-03-21/20230321.R](https://github.com/nrennie/tidytuesday/blob/main/2023/2023-03-21/20230321.R)

R4DS: https://github.com/rfordatascience/tidytuesday/blob/master/data/2023/2023-03-21/readme.md

## Data

```{r}
#| label: programming-data
#| message: false
languages <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2023/2023-03-21/languages.csv')
```

What are the variables?
```{r}
#| label: programming-data-head
head(languages)
```


## Exploratory analysis



```{r}
# data wrangling
plot_data <- languages |> 
  dplyr::filter(type == "pl") |> 
  dplyr::filter(line_comment_token %in% c("//", "#", ";")) |> 
  dplyr::select(title, appeared, line_comment_token, last_activity, language_rank) |> 
  tidyr::drop_na() |> 
  dplyr::mutate(label = paste("Comment token:", line_comment_token)) |> 
  dplyr::group_by(label) |> 
  dplyr::slice_head(n = 10) |> 
  dplyr::mutate(n = factor(dplyr::row_number(), levels = 1:10)) |> 
  dplyr::ungroup() |> 
  dplyr::select(label, n, title, appeared, last_activity, language_rank) |> 
  tidyr::pivot_longer(cols = c(appeared, last_activity),
               names_to = "type",
               values_to = "year") |>
  dplyr::mutate(title = paste0("<p>", title, "</p><p style='font-size:19pt;'>(Rank: ", language_rank, ")</p>"))
```


```{r}
# text
social <- "<span style='font-family:\"Font Awesome 6 Brands\";color:#66FF00;'>&#xf099;</span><span style='color:grey5;'>.</span><span style='font-family:share;color:#66FF00;'>@nrennie35</span><span style='color:grey5;'>..</span><span style='font-family:\"Font Awesome 6 Brands\";color:#66FF00;'>&#xf4f6;</span><span style='color:grey5;'>.</span><span style='font-family:share;color:#66FF00;'>fosstodon.org/@nrennie</span><span style='color:grey5;'>..</span><span style='font-family:\"Font Awesome 6 Brands\";color:#66FF00;'>&#xf09b;</span><span style='color:grey5;'>.</span><span style='font-family:share;color:#66FF00;'>nrennie</span><span style='color:grey5;'>..</span>"
subtitle <- "Of the 4,303 programming languages listed in the Programming Language DataBase, 205 use //, 101 use #, and 64 use ;
to define which lines are comments. 3,831 languages do not have a comment token listed."
```


## initial plot

```{r}
library(ggplot2)
basic_plot <- ggplot(plot_data) +
  geom_line(aes(x = year, y = n, group = n)) +
  geom_point(aes(x = year, y = n)) +
  facet_wrap(~label)
basic_plot
```

dumbbell plot

update to open ended

## Styling

### Colours

Why save colours as variables?

```{r}
bg_col <- "grey5"
main_col <- "#66FF00"
```

### Choosing a font

showtext
google fonts

```{r}
sysfonts::font_add_google("VT323", "vt")
sysfonts::font_add_google("Share Tech Mono", "share")
showtext::showtext_auto()
```

## Font awesome icons
 caption function

```{r}
# plot
ggplot(plot_data) +
  geom_line(aes(x = year, y = n, group = n),
            colour = "#66FF00",
            linewidth = 0.4) +
  geom_point(aes(x = year, y = n),
             pch = 22,
             fill = "grey5",
             colour = "#66FF00",
             size = 2) +
  ggtext::geom_richtext(aes(x = 1930, y = n, label = title),
            hjust = 0,
            family = "share",
            size = 8,
            fill = "transparent",
            label.colour = "transparent",
            vjust = 0.5,
            colour = "#66FF00") +
  facet_wrap(~label, nrow = 1) +
  scale_y_discrete(limits = rev) +
  scale_x_continuous(breaks = c(1970, 1990, 2010, 2030),
                     limits = c(1930, 2030),
                     expand = c(0, 0)) +
  labs(x = "",
       y = "",
       title = "Programming Languages",
       subtitle = subtitle,
       caption = social) +
  theme_minimal(base_size = 24,
                base_family = "share") +
  theme(plot.background = element_rect(fill = "grey5", colour = "grey5"),
        panel.background = element_rect(fill = "grey10",
                                        colour = alpha("#66FF00", 0.5),
                                        linewidth = 0.4),
        panel.grid.minor = element_blank(),
        panel.grid.major.x = element_line(colour = alpha("#66FF00", 0.5),
                                          linewidth = 0.2),
        panel.grid.major.y = element_blank(),
        strip.text = element_text(colour = "#66FF00", size = 26),
        axis.text.y = element_blank(),
        axis.text.x = element_text(colour = "#66FF00",
                                   vjust = 2),
        plot.title = element_text(colour = "#66FF00",
                                  family = "vt",
                                  face = "bold",
                                  size = 60),
        plot.subtitle = ggtext::element_textbox_simple(
          lineheight = 0.4,
          colour = main_col,
          hjust = 0,
          size = 28,
          margin = margin(b = 5)
        ),
        plot.caption = ggtext::element_textbox_simple(
          lineheight = 0.4,
          colour = "#66FF00",
          hjust = 0,
          size = 28,
          margin = margin(t = 5)
        ),
        axis.ticks = element_blank(),
        plot.margin = margin(10, 15, 5, 0))
```