---
title: "The #TidyTuesday Book"
subtitle: "Book Proposal"
author: "Nicola Rennie"
format: html
---

## Overview

R users
data visualisation
each chapter will go thorugh the code, design process of a different one of my tidytuesday visualisations. each chart will show a different set of packages

each chapter could be read independently

### Who is this book for?

- interested in data viz
- better at data viz in r
- designers thought process

### Competitors

data sketches
ggplot2 book

## Outline

* Introduction
  * Why visualise data?
  * Why use R for data visualisation?
  * What is #TidyTuesday?
  * A brief overview of my #TidyTuesday journey
  * Intended audience and required background knowledge
  * Information about R and package versions

* Chapter 1: [Programming languages](https://github.com/nrennie/tidytuesday/tree/main/2023/2023-03-21)
  * Dumbbell charts
  * Facets
  * Loading fonts
  * Font Awesome icons and social media captions

* Chapter 2: [Lemurs](https://github.com/nrennie/tidytuesday/tree/main/2021/24-08-2021)
  * Combining multiple plots with {patchwork}
  * Overlay a logo / images
  
* Chapter 3: [R Vignettes](https://github.com/nrennie/tidytuesday/tree/main/2022/2022-03-15)
  * Images as data in R
  * grobs

* Chapter 4: [Freedom in the World](https://github.com/nrennie/tidytuesday/tree/main/2022/2022-02-22)
  * geofacet

* Chapter 5: [UFO Sightings](https://github.com/nrennie/tidytuesday/tree/main/2023/2023-06-20)
  * Coloured text as a legend
  * NOn-standard facet labels
  
* Chapter 6: [Bird Sightings](https://github.com/nrennie/tidytuesday/tree/main/2023/2023-01-10)
  * Spatial smoothing
  * Maps

* Chapter 7: [UK Museums](https://github.com/nrennie/tidytuesday/tree/main/2022/2022-11-22)
  * gghighlight

* Chapter 8: [Cats](https://github.com/nrennie/tidytuesday/tree/main/2023/2023-01-31)
  * Annotations
  * Scatter plots
  * HTML formatted text

* Chapter 9: [Technology Adoption](https://github.com/nrennie/tidytuesday/tree/main/2022/2022-07-19)
  * Gauge charts

* Chapter 10: [Global Seafood](https://github.com/nrennie/tidytuesday/tree/main/2021/12-10-2021)
  * grid package

* Chapter 11: [Board Games](https://github.com/nrennie/tidytuesday/tree/main/2022/2022-01-25)
  * heatmaps
  * custom legends (mini chart as explainer)

* Chapter 12: {Creating data to build a specific idea}
  * [Football pitch](https://github.com/nrennie/tidytuesday/tree/main/2023/2023-04-04) or [clock](https://github.com/nrennie/tidytuesday/tree/main/2023/2023-09-12)

* Conclusion
  