# Visualizing spatial data {#sec-spatial-intro .unnumbered}

Spatial data refers to information about the physical location or shape of objects, and their relationships to each other. Examples of spatial data include latitude and longitude of a place; the boundary lines of a region; or a grid showing the elevation of an area.

* [Chapter]{.content-visible when-format="html"} @sec-doctors will discuss extracting country boundary data using the **`maps`** package, and then plotting choropleth maps with **`ggplot2`** to visualize the value of a variable for each country.

* [Chapter]{.content-visible when-format="html"} @sec-time-zones introduces you to the **`sf`** package for manipulating spatial data in R, and shows you how to plot geographic coordinate data. This chapter also covers co-ordinate systems.

* [Chapter]{.content-visible when-format="html"} @sec-house describes creating multiple area charts, each for a different region, and then arranging them in a grid that represents the underlying geography using the **`geofacet`** package.

In this section, you'll also learn how to create and arrange custom legends using **`patchwork`**, as well as repurposing elements of **`ggplot2`** charts to create more aesthetically pleasing titles.