# Making use of icons, fonts, and text {#sec-text-intro .unnumbered}

Fonts and text are not often the first elements to be considered when developing charts, perhaps since plots are often labelled as a better alternative to textual descriptions of data. That being said, careful use of font can make plots clearer and more interesting.

* [Chapter]{.content-visible when-format="html"} @sec-turbines details how to download icon fonts and then read in local font files using {sysfonts} and {showtext}. It also shows an example of using colored text as an alternative to a traditional legend through the {marquee} package.

* [Chapter]{.content-visible when-format="html"} @sec-cats describes an alternative approach to adding colored text with {ggtext}, and illustrates how to create data-driven annotations that update when your data does. This chapter also shows you how to write a function that adds social media icons to your plot captions.

* [Chapter]{.content-visible when-format="html"} @sec-nobel considers how to visualize text data, in a way that is both aesthetically pleasing but also brings more clarity than the default choice of word clouds.

This section also covers how to obtain data from an API using R, and writing functions to parameterize plots, enabling you to create different versions of the same chart for different subsets of data.