{
  "hash": "6c756bb7c8cf0ab3601c27afba94b4e1",
  "result": {
    "engine": "knitr",
    "markdown": "---\nfilters:\n  - line-highlight\nexecute: \n  freeze: auto\n---\n\n::: {.cell}\n\n:::\n\n\n\n\n\n\n# UK museums: highlighting line charts with **`gghighlight`** {#sec-museums}\n\nIn this chapter we'll consider different ways of visualising data that varies over time, aiming to avoid *spaghetti charts*, with the help of the **`gghighlight`** extension package. \\index{gghighlight}\n\n**Packages required in this chapter**:\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(dplyr)\nlibrary(gghighlight)\nlibrary(ggplot2)\nlibrary(ggtext)\nlibrary(purrr)\nlibrary(showtext)\nlibrary(sysfonts)\nlibrary(tibble)\nlibrary(tidyr)\nlibrary(tidytuesdayR)\nlibrary(viridis)\n```\n:::\n\n\n\n\n\n\n## Data\n\nThe [Mapping Museums](https://museweb.dcs.bbk.ac.uk/data) project [@museums_data] has collected data relating to over 4,000 museums in the UK, covering museums from 1960 onward. The data can be downloaded from the Mapping Museums website at {{< monolink \"https://museweb.dcs.bbk.ac.uk/home\" \"museweb.dcs.bbk.ac.uk\" >}}. It was also used as a TidyTuesday\\index{TidyTuesday} [@tidytuesday] data set in November 2022 (after being suggested by [Tom Mock](https://github.com/jthomasmock)), and we'll use that version for this chapter.\n\nLet's start by reading in the data using the **`tidytuesdayR`** R package [@tidytuesdayR] and looking at the definitions of the variables: \\index{tidytuesdayR!tt\\_load}\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntuesdata <- tt_load(\"2022-11-22\")\nmuseums <- tuesdata$museums\n```\n:::\n\n::: {.cell}\n\n:::\n\n\n\n\n\n\nThe data contains information for 35 different variables on 4191 museums. After the first `museum_id` columns, the next 8 columns provide information on the location of the museum - including address and co-ordinates. The next set of columns provides information about the museums such as whether it's an accredited museum, how it's governed, what types of items it has, and when it was open. Since this is a collated data set, information is also provided on the original source of the data for some of these variables. The remaining columns provide information on the area in which the museum is located, including information about different deprivation indices and geo-demographic group (type of area e.g. `\"University Towns and Cities\"`). A full glossary of the terms used can be found on the Mapping Museums website at {{< monolink \"https://museweb.dcs.bbk.ac.uk/glossary\" \"museweb.dcs.bbk.ac.uk/glossary\" >}}.\n\n## Exploratory work\n\nLet's start exploring what these variables look like!\n\n### Data exploration\n\nThere are many different aspects of this data we could inspect:\n\n* How are museums spread out across the UK? Is there a higher concentration of museums in more affluent areas?\n* What types of museums are most prevalent in the UK? Does this vary based on whether the museum is accredited?\n* How is the number of open museums changing over time? Are more museums opening than closing?\n\nSome of the variables, such as `DOMUS_Subject_Matter` have quite a lot of missing values which makes it more difficult to visualize and interpret them. Although these columns definitely warrant further exploration, we'll ignore them for now.\n\nGiven the wealth of information around deprivation indices (8 different variables), that's the first aspect of the data that jumps out. How does the number of museums vary by index of deprivation?\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbarplot(table(museums$Area_Deprivation_index))\n```\n\n::: {.cell-output-display}\n![Bar chart of number of museums per level of deprivation, with higher numbers of museums shown in levels 5 and 6.](museums_files/figure-html/fig-museums-barplot-1.png){#fig-museums-barplot fig-alt='Bar chart of 10 bars, one for each level of deprivation from 1 to 10, which exhibits a bell-shaped curve with the maximum value around 600.'}\n:::\n:::\n\n\n\n\n\n\nHere, `1` is the most deprived, and `10` is the least deprived. This is quite an interesting relationship - there have been more museums in places with a moderate level of deprivation compared to higher or lower level. This might feel a little bit counter-intuitive, we might expect there to be more museums in more affluent areas.\n\n::: {#tip-museums-graphics .callout-tip}\n\n## Alternative graphics packages\n\nThis book focuses on building graphics with **`ggplot2`** (and its various extension packages), in combination with using base R graphics for basic data exploration. However, these are not the only two graphics systems available for creating plots in R. \\index{lattice} \\index{tidyplots} \n\nJust a few of the many alternatives:\n\n* **`lattice`** [@lattice]: provides a framework for creating *trellis graphics* (also called small multiples or facet plots).\n\n* **`tidyplots`** [@tidyplots]: a newer graphics package aiming to make it easier to create publication-ready plots for scientific papers. It allows you to pipe together different functions, and add statistical summaries more easily. It also integrates with existing **`ggplot2`** functions.\n\nPackages for interactive visualizations are also discussed in @sec-house.\n\n:::\n\nBy looking at the total number of museums per index of deprivation in @fig-museums-barplot, we don't get the whole story. How many of these museums were open at once? How many are still open today? To get a better understanding of the relationship between deprivation and the number of museums, we could look at how the number of museums changed for each index of deprivation has changed since 1960 (the earliest date in the data set). Then we might be able to tell whether more are opening or closing, and how this varies across the different levels of deprivation.\n\n### Exploratory sketches\n\nWe have 10 deciles of deprivation, so we'll have 10 time series that we want to plot that show the number of museums over time. There are different options for plotting time series like this. We need to think about some different choices:\n\n* What type of *geometry* will we use? Lines, points, shaded areas? Lines are the most common approach for time series data.\n* Do we plot all 10 lines on the same chart and use color to denote the different levels of deprivation?\n* Or do we use faceting to split it into multiple smaller plots by deprivation index?\n\nIf we go with line charts, and faceting by deprivation index, that might look something like this: \n\n![Initial sketch of a faceted line chart showing change over time for each level of deprivation.](images/sketch-museums.png){#fig-museums-sketch fig-align=\"center\" fig-alt=\"Sketch of 10 small charts arranged in 2 rows and 5 columns, labelled from 1-10. Scribbles indicate the position of the title and caption text.\"}\n\nWe could achieve something this type of plot using `geom_line()` and `facet_wrap()` from **`ggplot2`** \\index{ggplot2!facet\\_wrap} \\index{ggplot2!geom\\_line}. We've talked about faceting before in @sec-programming but we haven't really thought much about the layouts of those facets. In @sec-programming, we used faceting with only 3 categories, where the layout choice is fairly obvious: either one column or one row. Here, we have a little bit more flexibility and we might want to think about controlling that layout.\n\nIf we leave it to the default options, **`ggplot2`** usually tries to coerce it into something *square-ish*. Here, it would likely give us a 3x4 grid filled with 10 plots (for the 10 levels of deprivation) and 2 blank spaces. It's not always possible, but plots without those blank spaces often look a lot cleaner and tidier. We could do either a 5x2 (or 2x5) grid, or a 10x1 (or 1x10) grid to fit our small multiple plots into a perfect rectangle. A 5x2 grid works better here since we don't want to make a very wide but very short plot.\n\n## Preparing a plot\n\nSo let's get started on preparing the data to create this plot!\n\n### Data wrangling\n\nThis is one of those very *real* datasets - the data wrangling is not straightforward for the data. In fact, the two columns relating to opening and closing dates are the two that will require the most attention.\n\nFirst, let's drop any columns that we don't actually need using the `select()` function from **`dplyr`** - we only need the `Year_opened`, `Year_closed`, and `Area_Deprivation_index` columns to calculate the number of museums open each year\\index{dplyr!select}. There are a few `NA` values in the `Area_Deprivation_index` column so we'll drop those rows using `drop_na()` from **`tidyr`**\\index{tidyr!drop\\_na}.\n\nNow let's start dealing with the year columns. If you look at the values, you'll notice that they're not exactly what you'd expect in a *year* column:\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(museums$Year_opened, 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"2012:2012\" \"1971:1971\" \"1984:1984\" \"1971:1971\"\n```\n\n\n:::\n\n```{.r .cell-code}\nhead(museums$Year_closed, 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"9999:9999\" \"2007:2017\" \"9999:9999\" \"2012:2012\"\n```\n\n\n:::\n:::\n\n\n\n\n\n\nEach entry is in fact two years, separated by a `:`. According to the [Mapping Museums glossary]([museweb.dcs.bbk.ac.uk](https://museweb.dcs.bbk.ac.uk/home)), this is because these are actually date ranges. For some museums, it wasn't possible to establish an exact opening or closing date, and instead a date range is given based on partial information. For example, a value of `\"2007:2017\"` means the museum opened (or closed) sometime between 2007 and 2017.\n\nLet's separate out these year values into four columns instead of two using the `separate_wider_delim()` function from **`tidyr`** \\index{tidyr!separate\\_wider\\_delim}. We separate based on the `:`, and create two new columns, `opened1` and `opened2` from the `Year_opened` column. We do the same thing for the `Year_closed` closed column. We also want to make sure that these new columns are numeric rather than character columns, so we use `mutate()` and `across()` from **`dplyr`** to convert them using `as.numeric()`\\index{dplyr!mutate} \\index{dplyr!across}. We can also convert the `Area_Deprivation_index` to a factor rather than a numeric and make sure the order is correct. \n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmuseum_subset <- museums |>\n  select(\n    Year_opened, Year_closed, Area_Deprivation_index\n  ) |>\n  drop_na() |>\n  separate_wider_delim(\n    Year_opened,\n    delim = \":\",\n    names = c(\"opened1\", \"opened2\")\n  ) |>\n  separate_wider_delim(\n    Year_closed,\n    delim = \":\",\n    names = c(\"closed1\", \"closed2\")\n  ) |>\n  mutate(\n    across(\n      c(opened1, opened2, closed1, closed2), as.numeric\n    ),\n    Area_Deprivation_index = factor(\n      Area_Deprivation_index,\n      levels = 1:10\n    )\n  )\n```\n:::\n\n\n\n\n\n\n::: {#tip-museums-separate .callout-tip}\n\n## Using `separate()` from **`tidyr`**\n\nIn older versions of **`tidyr`**, the `separate()` function would have been used instead of `separate_wider_delim()`. The `separate()` function has now been superseded. \\index{tidyr!separate}\n\n:::\n\nNow we need to think about how to deal with all of these *year* columns: \n\n* If the date before the `:` and the date after the `:` are the same, we want to treat it as an exact year and only keep one value.\n* If the dates do not match, we need to decide a way of choosing which year to use. The simplest approach is to take the midpoint of the date range. \n* If the value in the `Year_closed` column is `\"9999:9999\"`, this means that the museum is still open. \n\nLet's start with the last of these issues first. For the `closed1` and `closed2` columns, if the value is `\"9999\"`, we'll convert it to an `NA_real_` value. We can do this using a combination of `mutate()`, `across()`, and `if_else()` from **`dplyr`** \\index{dplyr!mutate} \\index{dplyr!across} \\index{dplyr!if\\_else}.\n\nThe remaining two issues can be dealt with at the same time using `case_when()` from **`dplyr`** \\index{dplyr!case\\_when}. We can create a new column called `closed` which:\n\n* if `closed1` and `closed2` are equal, takes this equal value;\n* if `closed1` and `closed2` are not equal, takes the value in the middle (rounded so that we work only with whole year values).\n\nThe same approach is then applied to create another new column called `opened`. There are no instances in the data where one of the closing dates is `NA` but the other is not, so we don't need to worry about that. We can also tidy up the output by dropping any columns we don't need, renaming the `Area_Deprivation_index` to something a little bit shorter and easier to work with, and arranging the data by level of deprivation. \\index{dplyr!rename} \\index{dplyr!arrange} \\index{dplyr!select} \n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmuseum_data <- museum_subset |>\n  mutate(across(\n    c(closed1, closed2),\n    ~ if_else(.x == 9999, NA_real_, .x)\n  )) |>\n  mutate(closed = case_when(\n    closed1 == closed2 ~ closed1,\n    closed1 != closed2 ~ round((closed2 + closed1) / 2)\n  )) |>\n  mutate(opened = case_when(\n    opened1 == opened2 ~ opened1,\n    opened1 != opened2 ~ round((opened2 + opened1) / 2)\n  )) |>\n  select(Area_Deprivation_index, opened, closed) |>\n  rename(deprivation = Area_Deprivation_index) |>\n  arrange(deprivation)\n```\n:::\n\n\n\n\n\n\nThis gives us data that looks like this:\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(museum_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 3\n  deprivation opened closed\n  <fct>        <dbl>  <dbl>\n1 1             1988     NA\n2 1             1984   2007\n3 1             1983     NA\n4 1             1969     NA\n5 1             1989     NA\n6 1             1995     NA\n```\n\n\n:::\n:::\n\n\n\n\n\n\nThe first entry in `museums_data` is a museum in the most deprived decile which opened in (approximately) 1988 and is still open.\n\nWhat we want to know is how many museums were open in a given year for each level of deprivation. Let's create a function that takes three inputs: a year of interest, a level of deprivation, and the `museum_data`. Inside the function, we can then `filter()` the data to only the level of deprivation we're interested in. Then we can count how many museums opened before or in the year we're interested in. We can then do the same for how many museums closed (remembering to deal with the `NA` values for museums that are still open). The difference between the two will be how many were open in that year. \\index{dplyr!filter}\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnum_year <- function(year, dep, data = museum_data) {\n  df <- filter(data, deprivation == dep)\n  num_open <- sum(df$opened <= year)\n  num_closed <- sum(df$closed <= year, na.rm = TRUE)\n  diff <- num_open - num_closed\n  return(diff)\n}\n```\n:::\n\n\n\n\n\n\nLet's test it works:\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnum_year(1980, 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 186\n```\n\n\n:::\n:::\n\n\n\n\n\n\nThere were 186 museums open in 1980, in an area in the third deprivation decile. Now, we need to run this function for every combination of year (from `1960` to `2021`) and deprivation level (from `1` to `10`). There are many different ways of doing this in R, and we're going to use the **`purrr`** package [@purrr]. We start by creating two variables with sequences of years and levels of deprivation - this is useful for testing if the code works because we can easily change it to a smaller number of years. Then we use `expand.grid` to create a `data.frame` with all of the combinations and pass this in as the first argument to `pmap_vec` from **`purrr`**. The second argument to `pmap_vec` is the function we want to apply (`num_year()`) that we defined above), where the first argument of `num_year()` comes from the first column of the grid of values, and the second argument from the second column. We can then convert the output into a matrix where each column is a level of deprivation, and each row is a year. \\index{purrr!pmap\\_vec} \n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nall_years <- 1960:2021\ndeps <- 1:10\noutput <- pmap_vec(\n  expand.grid(all_years, deps),\n  ~ num_year(year = .x, dep = .y)\n)\nresults <- matrix(output,\n  nrow = length(all_years),\n  byrow = FALSE\n)\ncolnames(results) <- 1:10\n```\n:::\n\n\n\n\n\n\nNow, our data looks like this:\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(results)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       1  2   3   4   5   6   7   8  9 10\n[1,] 103 78 110 125 125 124 122 110 76 51\n[2,] 103 78 112 132 125 131 126 113 77 53\n[3,] 104 78 113 138 129 135 129 117 83 58\n[4,] 105 79 118 140 136 140 130 123 85 60\n[5,] 105 79 122 144 139 145 135 126 86 64\n[6,] 106 80 123 148 143 147 137 128 89 67\n```\n\n\n:::\n:::\n\n\n\n\n\n\nWe're almost ready to start plotting our data! We just need to convert this into a `tibble()` (or `data.frame`), add the `year` column using `mutate()`, and put the data into a long format using `pivot_longer` from **`tidyr`** \\index{tibble!as\\_tibble} \\index{dplyr!mutate} \\index{tidyr!pivot\\_longer}. We want to end up with a 3 column data set, where the 3 columns are: `year`, `deprivation`, and `museums` (number of open museums).\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot_data <- results |>\n  as_tibble() |>\n  mutate(year = all_years) |>\n  pivot_longer(\n    -year,\n    names_to = \"deprivation\",\n    values_to = \"museums\"\n  ) |>\n  mutate(\n    deprivation = factor(deprivation, levels = 1:10)\n  )\n```\n:::\n\n\n\n\n\n\n### The first plot\n\nOne of most common approaches to visualising multiple time series, is to plot multiple lines on the same plot. Although we're already thinking about facets, it's still worth seeing what those line charts look like. It can help us to understand the overall variability of the data. We can create the initial plot using `ggplot()` to define the data and the aesthetic mapping with the `aes()` function. We have `year` on the x-axis, `museums` on the y-axis, and each line will have a different color based on `deprivation`. The actual lines are then added with `geom_line()`. \\index{ggplot2!geom\\_line} \\index{ggplot2!aes} \\index{ggplot2!ggplot} \\index{line chart}\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(\n  data = plot_data,\n  mapping = aes(\n    x = year,\n    y = museums,\n    color = deprivation\n  )\n) +\n  geom_line()\n```\n\n::: {.cell-output-display}\n![A line chart of total number of museums open per year for each level of deprivation, with the overlapping lines resembling spaghetti!](museums_files/figure-html/fig-museums-basic-plot-1-1.png){#fig-museums-basic-plot-1 fig-alt='A line chart with 10 lines showing the number of open museums for each level of deprivation. Many of the lines overlap and are similar colors, making it difficult to read the values. Line go from 1980 to 2020 and show a general increase from around 100 to 500.'}\n:::\n:::\n\n\n\n\n\n\nThere are a few things that jump out immediately about this plot:\n\n* The variability is increasing over time: in 1960 the gap between the highest and lowest values is much smaller than the gap between the highest and lowest values in 2020.\n* It's difficult to tell which line belongs to which level of deprivation: some of the colors are quite similar, many of the lines intersect, and the order of the legend is generally in reverse to the order of the lines.\n* It's what we might call a *spaghetti plot*: it shows the overall trend across all levels, but it's hard to tell the difference between different levels of deprivation.\n\nLet's go back to our previous idea, and try separating out the deprivation levels into different facets. We can do this using `facet_wrap(~deprivation, nrow = 2)` , with the `nrow` argument used to create that 5x2 grid we talked about earlier. Let's also try changing `geom_line()` to `geom_area()`. Although line charts and area charts can both show the same data, line charts often cause us to focus more on the trend over time. In contrast, area charts often cause us to focus on the total volume over time - helping to highlight differences in total number of open museums over time rather than just increases and decreases. Remember to also change `color` to `fill` in the aesthetic mapping! \\index{ggplot2!geom\\_area} \\index{ggplot2!facet\\_wrap} \\index{area chart}\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(\n  data = plot_data,\n  mapping = aes(x = year, y = museums, fill = deprivation)\n) +\n  geom_area() +\n  facet_wrap(~deprivation, nrow = 2)\n```\n\n::: {.cell-output-display}\n![An area chart of total number of museums open per year for each level of deprivation, with the each deprivation level in a different facet.](museums_files/figure-html/fig-museums-basic-plot-2-1.png){#fig-museums-basic-plot-2 fig-alt='10 area charts arranged in a 5x2 grid, each one a different color and labeled based on deprivation. A legend appears on the right hand side. Areas in level 1, 2, and 10 appear smaller.'}\n:::\n:::\n\n\n\n\n\n\nThis tells a similar story to the initial bar chart in @fig-museums-barplot - there are more museums open in the areas with moderate levels of deprivation. This plot still isn't ideal, for a couple of reasons:\n\n* The number of open museums in 1960 is different in each faceted plot: since they all start at different levels, it makes it more difficult to compare the relative increases or decreases.\n* It's hard to directly compare one facet to another since each facet only contains one trend line: we have to imagine overlaying the lines in our head to compare one trend line to another.\n\nWe could solve these problems by making two changes:\n\n* Rescale the data based on the number of museums open in 1960; and\n* Show all 10 lines on each faceted plot but highlight only one relating to each level of deprivation. \n\n### Highlighting with **`gghighlight`**\n\nThe second change can be implemented easily using the **`gghighlight`** package [@gghighlight]. **`gghighlight`** is a **`ggplot2`** extension package, specifically designed for highlighting points and lines based on some conditions. Let's switch back to `geom_line()` and add `gghighlight()`. We set `use_direct_label = FALSE` because **`gghighlight`** will otherwise add a label to each highlighted line - unnecessary since each line is labelled by it's facet label already. \\index{gghighlight!gghighlight} \\index{ggplot2!geom\\_line} \\index{line chart}\n\n\n\n\n\n\n::: {.cell source-line-numbers='11'}\n\n```{.r .cell-code}\nggplot(\n  data = plot_data,\n  mapping = aes(\n    x = year,\n    y = museums,\n    color = deprivation\n  )\n) +\n  geom_line() +\n  facet_wrap(~deprivation, nrow = 2) +\n  gghighlight(use_direct_label = FALSE)\n```\n\n::: {.cell-output-display}\n![A line chart of total number of museums open per year for each level of deprivation, with the each deprivation level in a different facet and individual lines highlighted.](museums_files/figure-html/fig-museums-basic-plot-3-1.png){#fig-museums-basic-plot-3 fig-alt='10 line charts arranged in a 5x2 grid, each with the same 10 lines, but one a different color and labeled based on deprivation. Values range from around 100 to 500. A legend appears on the right hand side.'}\n:::\n:::\n\n\n\n\n\n\nWe can also perform an additional bit of data wrangling to rescale the values by their 1960 levels. We start by filtering the data to only include data from the year 1960 and keeping only the `deprivation` and `museums` columns \\index{dplyr!filter} \\index{dplyr!select}. Then, we join this baseline data back to our original data based on the `deprivation` level, and for each year calculate the percentage change since 1960 and save it in a new column called `change`. \\index{dplyr!mutate} \\index{dplyr!rename} \\index{dplyr!left\\_join} \\index{dplyr!select}\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlookup <- plot_data |>\n  filter(year == 1960) |>\n  select(deprivation, museums)\n\nnew_plot_data <- plot_data |>\n  left_join(lookup, by = \"deprivation\") |>\n  rename(\n    museums = museums.x,\n    museums_1960 = museums.y\n  ) |>\n  mutate(\n    change = (\n      100 * (museums - museums_1960) / museums_1960)\n  ) |>\n  select(year, deprivation, change)\n```\n:::\n\n\n\n\n\n\nWe can then re-do our line chart using the rescaled `change` data on the y-axis instead:\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbasic_plot <- ggplot(\n  data = new_plot_data,\n  mapping = aes(x = year, y = change, color = deprivation)\n) +\n  geom_line() +\n  facet_wrap(~deprivation, nrow = 2) +\n  gghighlight(use_direct_label = FALSE)\nbasic_plot\n```\n\n::: {.cell-output-display}\n![A line chart of percentage increase in museums (compared to 1960) for each level of deprivation, with the each deprivation level in a different facet and individual lines highlighted.](museums_files/figure-html/fig-museums-basic-plot-4-1.png){#fig-museums-basic-plot-4 fig-alt='10 line charts arranged in a 5x2 grid, each with the same 10 lines, but one a different color and labeled based on deprivation. Values are percentages ranging from around 0 to 300. A legend appears on the right hand side.'}\n:::\n:::\n\n\n\n\n\n\nThis is starting to look promising, but there are still ways that we can style our chart to improve it.\n\n## Advanced styling\n\nSo what can we do to make this chart better?\n\n* We can get rid of the legend. The colors are based on the levels of deprivation, which are already labelled on the facet titles.\n* The default choice of color isn't great - they're not grayscale printing friendly, and they're not colorblind friendly either. \n* It's not immediately clear what this chart shows: it could do with some text to explain what's going on.\n\n### Colors\n\nLet's get started with choosing some colors. As discussed in @sec-programming, we'll save color codes as variables: either using hex codes or color names. Let's use `\"black\"` for text, and `\"#fafafa\"` for the background color. The use of a light gray rather than white for the background is primarily personal preference - it's less glaringly bright on a screen. Although, you do have to be a bit more careful around contrast of text against the background - hence the black text. \\index{color}\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbg_col <- \"#FAFAFA\"\ntext_col <- \"black\"\n```\n:::\n\n\n\n\n\n\nFor the colors of the lines, we can use the **`viridis`** package [@viridis]. The **`viridis`** package provides multiple different color palettes which are designed to be visually pleasing, perceptually-uniform ,and colorblind friendly. The default viridis palette includes purples, blues, greens, then yellows. Viridis color palettes are most commonly used with continuous data, rather than categorical data. However, since the categories that we wish to color (levels of deprivation) are ordered, they will work well here too. The **`viridis`** package includes functions to add the colors to plots made with **`ggplot2`**. Here, we use the `scale_color_viridis()` function, specify that we want a discrete palette and that the lowest values should have the yellow colors with `direction = -1` \\index{viridis!scale\\_color\\_viridis}.\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncol_plot <- basic_plot +\n  scale_color_viridis(\n    discrete = TRUE,\n    direction = -1\n  )\ncol_plot\n```\n\n::: {.cell-output-display}\n![An updated version of the previous chart with colors chosen from the {viridis} R package.](museums_files/figure-html/fig-museums-style-plot-1-1.png){#fig-museums-style-plot-1 fig-alt='10 line charts arranged in a 5x2 grid, each with the same 10 lines, but one a different color and labeled based on deprivation. Values are percentages ranging from around 0 to 300. A legend appears on the right hand side. Lines are colored yellows, blues, and purples.'}\n:::\n:::\n\n\n\n\n\n\n### Text and fonts\n\nLet's start by loading in a different typeface using `font_add_google()` from **`sysfonts`** and setting font options with **`showtext`**\\index{sysfonts!font\\_add\\_google} \\index{showtext!showtext\\_auto} \\index{showtext!showtext\\_opts}. *Raleway* is a minimalist, sans serif typeface, and we'll use it for both body text and title text. We can save it as a single variable, `body_font`.\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfont_add_google(name = \"Raleway\")\nshowtext_auto()\nshowtext_opts(dpi = 300)\nbody_font <- \"Raleway\"\n```\n:::\n\n\n\n\n\n\n::: {#tip-museums-typeface .callout-tip}\n\n## Typeface vs. font vs. font family\n\nThomas Lin Pederson's blog post about fonts in R [@Pedersen2025] highlights the different meanings of the words *typeface* and *font* (family), which are often (incorrectly) used interchangeably:\n\n* **Typeface**:the design of a set of characters e.g. *Arial*\n\n* **Font**: a specific style and size of that typeface e.g. *Arial Bold 12pt*\n\n* **Font family**: a group of related fonts that share the same typeface but vary in styles e.g. *Arial Bold* and *Arial Italic*\n\nAlthough these terms do have different meanings, in **`ggplot2`**, the `family` argument is often used to specify the typeface so you may see the terms used interchangeably in this book.\n\n:::\n\nWe also need to define a title, subtitle, and caption. Adding a question as a title can help guide readers towards what you want them to see, but also force them to look for themselves. Here, we ask *Are there fewer museums opening in more deprived areas?* in the title - telling readers to look at changes across the levels of deprivation, but not giving them the answer straight away. \n\nThe subtitle then goes onto explain what the answer is, and exactly what is shown in the chart. The caption is more extended here than you may see in many charts because it explains more about the source of the data and what the variables actually are. Understanding definitions of variables isn't something we should ever take for granted. Unless you are already familiar with indices of deprivation, it may not be clear that `1` means higher levels of deprivation. \n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntitle <- \"Are there fewer museums opening in more deprived areas?\"\nst <- \"The change in the estimated number of open museums since 1960 is significantly lower in areas with higher levels of deprivation. *Since around 2000, the number of open museums has stagnated across all areas, regardless of deprivation index. However, the rate of growth prior to this stagnation is lower in more deprived areas.\"\ncap <- \"*The Index of Multiple Deprivation (IMD) measures the relative deprivation of geographic areas in the UK, aggregating different dimensions (income, employment, education, health, crime, housing, and living environment). The index ranges from 1 (most deprived) to 10 (least deprived).<br><br>**In some instances it has been impossible to establish an exact opening or closing date for a museum. In these cases, museums’ opening and closing dates are taken to be the mid point of a specified range of possible dates.<br><br>N. Rennie | Data: museweb.dcs.bbk.ac.uk\"\n```\n:::\n\n\n\n\n\n\n::: {#tip-museums-html .callout-tip}\n\n## Adding line breaks using `<br>`\n\nThe caption includes HTML line breaks, `<br>`, since we'll be using `element_textbox_simple()` from **`ggtext`** for processing the text elements as we've done in previous chapters. \\index{ggtext!element\\_textbox\\_simple}\n\n:::\n\nLet's add the title, subtitle, caption, and a y-axis label in using the `labs()` function. We can also remove the default column name label on the x-axis as it's very clear that the x-axis shows years. \\index{ggplot2!labs}\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntext_plot <- col_plot +\n  labs(\n    title = title, subtitle = st, caption = cap,\n    x = \"\",\n    y = \"% change in estimated number of\\nopen museums since 1960**\"\n  )\n```\n:::\n\n\n\n\n\n\n### Adjusting themes\n\nNow we need to edit the `theme()` elements to apply the text fonts and styles, edit the background colors, and remove the legend. \\index{ggplot2!theme}\n\nIn **`ggplot2`**, the axis limits are chosen automatically based on the range of the data. It's often useful to chose limits (and breaks) that are *nice* - it makes it easier to calculate where other values are. We can set `scale_y_continuous(limits = c(0, 300))` to make the range of the y-axis between 0 and 300. We can also set `coord_cartesian(expand = FALSE)` to remove the extra space around the plot area that is added by default - giving a slightly cleaner look. Using `theme_minimal()` as a base, we can set the default font size and family using `base_size = 7` and `base_family = body_font`. \\index{ggplot2!theme\\_minimal} \\index{ggplot2!coord\\_cartesian} \\index{ggplot2!scale\\_y\\_continuous}\n\nSetting `legend.position = \"none\"` removes the legend on the right hand side. The `plot.title.position = \"plot\"` and `plot.caption.position = \"plot\"` arguments make sure that the title, subtitle, and caption text are all aligned with the left side of the plot area. The default is to align with the edge of the panel area (the area shaded gray by default), which doesn't look good when you have long axis labels, or a multiline axis title on the y-axis.\n\nThe `panel.spacing` argument controls how close the facets are to each other -  this can help to stop the year labels on side-by-side plots from overlapping. Setting `plot.margin = margin(10, 15, 10, 10)` adds some extra space around the outside of the plot, with the higher value on the right hand side compensating and balancing out the space from the axis title on the left hand side. The `plot.background` and `panel.background` arguments set the background color of the plot and panel areas to be the `bg_col` variable previously defined.\n\nFor the `plot.title`, `plot.subtitle`, and `plot.caption`, arguments, we use `element_textbox_simple()` from **`ggtext`** to make sure that any Markdown or HTML syntax is processed, and to automatically wrap the text in the subtitle and caption. The text is all left-aligned, with a `lineheight` of `0.5`, and set to use the `text_col` variable for the color. The title font is made slightly larger and in bold. The `axis.text` is also set to be `text_col` colored with a `lineheight` of `0.5` using `element_text()`. \\index{ggplot2!element\\_text} \\index{ggplot2!theme}\n\nNow, we have our final plot:\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntext_plot +\n  scale_y_continuous(limits = c(0, 300)) +\n  coord_cartesian(expand = FALSE) +\n  theme_minimal(base_size = 7, base_family = body_font) +\n  theme(\n    legend.position = \"none\",\n    plot.title.position = \"plot\",\n    plot.caption.position = \"plot\",\n    panel.spacing = unit(1, \"lines\"),\n    plot.margin = margin(10, 15, 10, 10),\n    plot.background = element_rect(\n      fill = bg_col, color = bg_col\n    ),\n    panel.background = element_rect(\n      fill = bg_col, color = bg_col\n    ),\n    plot.title = element_textbox_simple(\n      color = text_col,\n      lineheight = 0.5,\n      size = rel(1.2),\n      face = \"bold\",\n      margin = margin(b = 5)\n    ),\n    plot.subtitle = element_textbox_simple(\n      color = text_col,\n      lineheight = 0.5\n    ),\n    plot.caption = element_textbox_simple(\n      hjust = 0,\n      color = text_col,\n      lineheight = 0.5\n    ),\n    axis.text = element_text(\n      color = text_col,\n      lineheight = 0.5\n    )\n  )\n```\n\n::: {.cell-output-display}\n![A styled version of the previous plot - with a custom font, colored background, and better spacing.](museums_files/figure-html/fig-museums-style-plot-3-1.png){#fig-museums-style-plot-3 fig-alt='10 line charts arranged in a 5x2 grid, each with the same 10 lines, but one a different color and labeled based on deprivation. Values are percentages ranging from around 0 to 300. Lines are colored yellows, blues, and purples. No legend appears,but title, subtitle, and caption text have appeared.'}\n:::\n:::\n\n\n\n\n\n\nAnd we can save it to a file using `ggsave()` as we did in @sec-programming. In @sec-programming, when saving our final plot to a file, we saved it as a PNG file. However, that's not the only option. We could also have saved in as a JPG, PDF, TIFF, or SVG (to name just a few options). So how do we decide what file type to use? \\index{ggplot2!ggsave}\n\nFormats such as PNG and JPG save *raster* images i.e. information is stored about each pixel. This means that they are able to capture highly detailed information. However, this also means that file sizes can be large. Raster images also don't scale well - when you increase the size of an image, it tends to become blurry and lower in quality. Formats such as PDF or SVG are *vector* images i.e. information is stored about each line and shape in the image. This means it's easier to rescale without losing quality, and file sizes can be smaller (at least for graphics that are not excessively complex).\n\nRaster images tend to be better for complex visualisations and images, or when fixed resolution is preferred such as in a website. Vector images tend to be better for graphics that are likely to need resizing or be interactive. For the remainder of this book, we'll continue to save in PNG format for consistency in the print version of the book. \\index{image format}\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggsave(\n  filename = \"museums.png\",\n  width = 5,\n  height = 0.67 * 5\n)\n```\n:::\n\n\n\n\n\n\n## Reflection\n\nIs there anything that could still be improved about this plot? The axis text denoting the years only appears on the bottom row of faceted plots. This makes it a little bit tricky to see what's going on in the first row without first looking at the years in the row below. It's a fairly minor point, but adding year labels to the top row would just make it easier for a reader.\n\nWe removed the legend from the plot with the reason that *the colors are based on the levels of deprivation, which are already labelled on the facet titles*. This same argument could be used to remove the colors altogether. There's no need to use color here to denote the deprivation levels when the deprivation levels are given by the facet titles. Especially since the yellow color is harder to see against the pale background color. Using a stronger color e.g. red for all highlighted lines, would be better for making the lines stand out, and reduce confusion about what the colors mean. \\index{color}\n\n::: {.content-visible when-format=\"html\"}\n\nEach plot created during the process of developing the original version of this visualization was captured using **`camcorder`**, and is shown in the gif below. If you'd like to learn more about how **`camcorder`** can be used in the data visualization process, see @sec-camcorder.\n\n![](images/uk-museums.gif){fig-align=\"center\" fig-alt=\"Gif showing the process of creating the final line chart, going through iterations of area charts first.\"}\n\n:::\n\n## Exercises\n\n* Edit the visualization to use a single color (of your choice) to highlight each line, instead of the `viridis` color palette.\n\n* Edit the facet labels to indicate directly on the chart which ones are the *least deprived* and *most deprived*.\n",
    "supporting": [
      "museums_files\\figure-html"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}