---
title: "The #TidyTuesday Cookbook"
subtitle: "Book Proposal"
author: "Nicola Rennie"
format: pdf
---

**Proposed Title**: The #TidyTuesday Cookbook

**Proposed Subtitle**: A Case Study Approach to Learning Data Visualisation with {ggplot2}

## Overview

#TidyTuesday is a weekly social data project which aims to make learning to work with data easier, by providing real-world datasets. Participants are encouraged to explore the data each week, create an output such as a data visualisation, and share it (and the code) with the community. After three years of weekly contributions, I have worked with around 150 datasets and created over 150 data visualisations. This book will present a subset of these visualisations, and describe the process used to create them. Each chapter will cover a different data visualisation, showing: the data exploration process; the choice of data visualisation type; the initial design ideas with hand-drawn sketches; the first build of a plot; and the iterative process of styling plots. Full code will be provided and explained for each step of the creative process.

The visualisations in this book will be created completely in R, primarily using {ggplot2} and the various extension packages. Unlike other books on data visualisation, this book shows the "hacky" workarounds and the unusual types of plots that can be made using the {ggplot2} ecosystem. Due to the case study approach taken in this book, each chapter can be read independently as a single "how to" guide for a specific visualisation. The book as a whole will introduce a wide range of {ggplot2} extension packages across the various chapters.

This book is primarily aimed at those who wish to develop their data visualisation skills in R. It could serve as a course textbook for courses in data visualisation at either undergraduate or postgraduate level, covering both conceptual and technical aspects of creating data visualisations. The case study nature of the book also means that choosing a subset of one or two chapters could provide material for shorter data visualisation workshops. Readers of this book may find a basic knowledge of R, more specifically of the {tidyverse} ecosystem, useful though all code used in examples is fully explained. Readers do not need to be experienced in {ggplot2}, though this book will also be of interest to those who are. Readers of this book will be of interest to those who are already familiar with R (including {ggplot2}), and wish to develop their skills in designing data visualisations further. It will also be of interest to those who already design data visualisations using other tools, and want to learn how to do the equivalent in R.


## Author

[Nicola Rennie](https://nrennie.rbind.io/) is a Lecturer in Health Data Science within the [Centre for Health Informatics, Computing, and Statistics](https://chicas.lancaster-university.uk/index.html) at Lancaster University. She holds a PhD in Statistics and Operational Research, focusing on analysing and visualising transport demand. Her current research is focused on applications of statistics and machine learning to health-related data, communicating statistics, and the effective teaching of data science. She has experience of teaching at both undergraduate and postgraduate level, in courses covering fundamentals of data science, population health, and statistical programming. Nicola has also previously worked in data science consultancy, and delivered training courses covering topics including advanced data visualisation with R, statistical modelling, and reproducible reporting. She is the author and maintainer of several R packages, including multiple {ggplot2} extension packages. Nicola is a regular speaker at R and data science meetups, and is the current chapter organiser of R-Ladies Lancaster. She is co-author of the Royal Statistical Society's [Best Practices for Data Visualisation Guide](https://royal-statistical-society.github.io/datavisguide/), and an active member of the Royal Statistical Society. Several of her data visualisations have been long-listed at the Information is Beautiful Awards.


## Closely related titles

* **[ggplot2: Elegant Graphics for Data Analysis](https://ggplot2-book.org/). Hadley Wickham, Danielle Navarro, and Thomas Lin Pedersen. 3rd Edition. 2023.**
This book introduces the *Grammar of Graphics*. It primarily focuses on the concepts behind the core {ggplot2} package, and doesn't provide worked examples of how to create complex visualisations, or extend into the wider array of {ggplot2} packages. It does not discuss how to design or conceptualise a visualisation idea.

* **[R Graphics Cookbook](https://r-graphics.org/). Winston Chang. 2nd Edition. 2023.** This book shows readers how to make various charts in R, primarily using {ggplot2}, though also making use of some base R and additional packages. It covers aspects such as how to make a violin chart, how to make a line chart etc., as well as loading data and exporting image files. It includes instructions about customising different aspects of plots, but the customisation is simple and straightforward. It does not cover aspects such as selection of chart type.

* **[Data Sketches](https://www.datasketch.es/). Nadieh Bremer and Shirley Wu. 2021.**
This book documents the creative process behind 24 data visualisation projects. It includes information on data collection, sketches, and coding data visualisations. This book is not R specific and, though it provides some code explanations, it does not provide full code for each chart or focus on the technical aspects of how to write code to produce the examples.


## Chapter outline

* Introduction
  * Why visualise data?
  * Why use R for data visualisation?
  * What is #TidyTuesday?
  * Intended audience and required background knowledge
  * Information about R and package versions
  
### Part 1: Common charts don't need to be boring!

* Chapter 1: [Programming languages](https://github.com/nrennie/tidytuesday/tree/main/2023/2023-03-21)
  * Exploratory data analysis
  * Initial sketches
  * Creating points and lines with ggplot2
  * Building a dumbbell chart
  * Facetting with `facet_wrap()`
  * Loading fonts in R with {showtext}

* Chapter 2: [Bee colony losses](https://github.com/nrennie/tidytuesday/tree/main/2022/2022-01-11)
  * Exploratory data analysis
  * Initial sketches
  * Scatter plots
  * Poisson sampling
  * Facetting with `facet_grid()`

* Chapter 3: [UK Museums](https://github.com/nrennie/tidytuesday/tree/main/2022/2022-11-22)
  * Exploratory data analysis
  * Initial sketches
  * Area charts
  * Line charts
  * Highlighting with {gghighlight}
  
* Chapter 4: [Board Games](https://github.com/nrennie/tidytuesday/tree/main/2022/2022-01-25)
  * Exploratory data analysis
  * Initial sketches
  * Heatmaps
  * Custom legends
  * Combining multiple plots with {patchwork}

### Part 2: Making use of icons, fonts, and text

* Chapter 5: [Starbucks](https://github.com/nrennie/tidytuesday/tree/main/2021/21-12-2021)
  * Exploratory data analysis
  * Initial sketches
  * Icons with {emojifont}
  * An alternative to heatmaps
  
* Chapter 6: [UFO Sightings](https://github.com/nrennie/tidytuesday/tree/main/2023/2023-06-20)
  * Exploratory data analysis
  * Initial sketches
  * Creating your own facet labels
  * Coloured text as a legend
  * Font Awesome icons
  * Creating social media captions
  * Positional text with labs() - see Chapter 8
  
* Chapter 7: [Cats](https://github.com/nrennie/tidytuesday/tree/main/2023/2023-01-31)
  * Exploratory data analysis
  * Initial sketches
  * Annotations
  * Scatter plots
  * HTML formatted text
  
* Alternative icon chapter: [Trash Wheels](https://github.com/nrennie/tidytuesday/tree/main/2024/2024-03-05)
  * Exploratory data analysis
  * Initial sketches
  * Try with {waffle} bar chart
  * Redo manually with {emojifont}
  
* Alternative text chapter: [Leap Day](https://github.com/nrennie/tidytuesday/tree/main/2024/2024-02-27)
  * Exploratory data analysis
  * Initial sketches
  * Trigonometry for text positioning
  * Coloured text
  * Purpose not always accuracy of information transfer
  * R as a design tool
  
### Part 3: Visualising spatial data

* Chapter 8: [Doctors in an ageing population](https://github.com/nrennie/tidytuesday/tree/main/2023/2023-01-03)
  * Bring your own data: common open data sources
  * Exploratory data analysis
  * Initial sketches
  * Basic maps in {ggplot2}

* Chapter 9: [Bird Sightings](https://github.com/nrennie/tidytuesday/tree/main/2023/2023-01-10)
  * Exploratory data analysis
  * Initial sketches
  * Spatial data with {sf}
  * Spatial smoothing with inverse distance weighting
  * Cropping raster files

* Chapter 10: [Freedom in the World](https://github.com/nrennie/tidytuesday/tree/main/2022/2022-02-22)
  * Exploratory data analysis
  * Initial sketches
  * Map alternatives with {geofacet}
  * Hexagon tiled maps

### Part 4: Working with images

* Chapter 11: [Lemurs](https://github.com/nrennie/tidytuesday/tree/main/2021/24-08-2021)
  * Exploratory data analysis
  * Initial sketches
  * Adding images with {cowplot}

* Chapter 12: [R Vignettes](https://github.com/nrennie/tidytuesday/tree/main/2022/2022-03-15)
  * Exploratory data analysis
  * Initial sketches
  * Images as data with {ggimage}
  * Editing facet labels
  * What are grobs?
  * Editing plots with grid
  
* Chapter 13: [Global Seafood](https://github.com/nrennie/tidytuesday/tree/main/2021/12-10-2021)
  * Exploratory data analysis
  * Initial sketches
  * Drawing with the {grid} package
  * Creating slides with {grid} and {ggplot2}

### Part 5: Weird and wonderful: completely custom charts

* Chapter 14: [Technology Adoption](https://github.com/nrennie/tidytuesday/tree/main/2022/2022-07-19)
  * Exploratory data analysis
  * Initial sketches
  * The {ggforce} extension
  * Donut charts
  * Gauge charts
  
* Chapter 15: [Premier League](https://github.com/nrennie/tidytuesday/tree/main/2023/2023-04-04)
  * Exploratory data analysis
  * Initial sketches
  * Building a football pitch
  * Adding footballs with {emojifont}
  * An alternative with {ggsoccer}
  
* Chapter 16: [The Global Human Day](https://github.com/nrennie/tidytuesday/tree/main/2023/2023-09-12)
  * Exploratory data analysis
  * Initial sketches
  * Voronoi charts in R
  * Circular voronoi charts in R
  * Building a clock face
  
* Conclusion
  * Template files for #TidyTuesday
  * Helper functions
  * {camcorder} for gifs
  * Other packages I didn't mention but use

* Acknowledgements
