# Introduction

## Why visualise data?

## What is #TidyTuesday?

## Background knowledge

## A note about R code

All code in this was created using `r R.version.string`, and a complete list of package versions can be found in the Appendix.

### Base R pipe vs {magrittr} pipe

In R, the pipe operator *takes the thing on its left and passes it along to the function on its right* [@r4ds]. You can find a full description of the pipe operator in [R for Data Science](https://r4ds.hadley.nz/data-transform#sec-the-pipe). The pipe (`%>%`) was first introduced to R via the {magrittr} package. Since version 4.1.0 of R, a version of the pipe (`|>`) has existed in base R. The base R version of the pipe is used throughout the book. Although there are some difference between the two version of the pipe, in this book, they can be used interchangeably.

### Namespacing

Namespacing (the pre-fixing of functions with the package name and `::`) is used for all packages except {ggplot2} and base R packages. Namespacing is useful for two reasons (i) from a learning perspective, it makes it easier to recognise where functions come from and how they connect together, and (ii) from a programming perspective, it reduces conflicts and errors - something we all want less of! 

### Changes to code

You may notice that some of the final images differ slightly from those initially created and published on social media. You might also find some small differences in the code used to produce them if you compare the contents of this book to original scripts in the [GitHub repository](https://github.com/nrennie/tidytuesday). These differences are primarily due to two reasons: (i) packages have been updated and code has been changed to use newer syntax; (ii) some aspects have been omitted here to avoid explaining *everything* in Chapter 1 - but they are all covered and linked to in later chapters!; or (iii) I found a more efficient way of doing something. Any changes are clearly labelled and discussed.

